name = "Overpass"
uuid = "834259d5-5bc3-4baf-8c23-ac7b5902f5e3"
authors = ["Gregor Wehrle <171450664+gwehrle@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
